- name: send email
  gather_facts: true
  hosts: all
  mail:
     subject: Test Mail Module
     body: this is a test body message 
     to: ahuchcha@redhat.com 
     from: tower.example.com
     
     

