- name: test vault
  gather_facts: true
  hosts: all
  vars:
    Data: "{{ lookup('hashi_vault', 'secret={{ secret }} url={{ url }} token={{ token }} validate_certs=no') }}"
    AWS_ACCESS_KEY: "{{ Data['access_key'] }}" 
    AWS_SECRET_KEY: "{{ Data['secret_key'] }}"
    AWS_SECURITY_TOKEN: "{{ Data['security_token'] }}"

  tasks:
    -
      debug:
        msg: "{{ AWS_ACCESS_KEY }}, {{ AWS_SECRET_KEY }}, {{ AWS_SECURITY_TOKEN }}"
        
    - name: Copy file
      copy:
        src: "{{ lookup('env','MY_CLOUD_INI_FILE') }}"
        dest: /tmp
