- name: test vault
  gather_facts: true
  hosts: localhost
 
  tasks:
   -
      debug:
        msg: "{{ lookup('hashi_vault', 'secret={{ secret }} url=http://vm253-27.gsslab.pnq2.redhat.com:8200 token={{ token }} validate_certs=no') }}"
